name: Android CI

on:
  workflow_dispatch

  #push:
  #branches: [ "main" ]

jobs:
  CI-Create-Release:
    name: Create a new release on GitHub
    runs-on: ubuntu-latest

    env:
      ANDROID_KEY_ALIAS: ${{secrets.ANDROID_KEY_ALIAS}}
      ANDROID_KEY_PASSWORD: ${{secrets.ANDROID_KEY_PASSWORD}}
      ANDROID_SIGNING_KEY: ${{secrets.ANDROID_SIGNING_KEY}}
      ANDROID_SIGNING_KEY_PASSPHRASE: ${{secrets.ANDROID_SIGNING_KEY_PASSPHRASE}}
      ANDROID_STORE_PASSWORD: ${{secrets.ANDROID_STORE_PASSWORD}}
      ANDROID_GITHUB_TOKEN: ${{secrets.ANDROID_GITHUB_TOKEN}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: Install bundler & Fastlane
        run: |
          gem install bundler:2.3.25
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Generate .jks file
        run: |
          echo "${{secrets.ANDROID_SIGNING_KEY}}" > keystore.jks.asc
          gpg -d --passphrase "${{secrets.ANDROID_SIGNING_KEY_PASSPHRASE}}" --batch keystore.jks.asc > app/keystore.jks

      - name: Config Git account's identity
        run: |
          git config --global user.email "rinnbiesun@gmail.com"
          git config --global user.name "Rinnbie Sun"

      - name: Create GitHub release
        run: bundle exec fastlane github_release

    #- name: Grant execute permission for gradlew
    # run: chmod +x gradlew

    #- name: Build with Gradle
    # run: ./gradlew build
